import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "<src>/styles/Home.module.css";
import { useEffect, useState } from "react";
import { Container, Grid } from "@mui/material";
import classes from "<src>/styles/index.styles";
import LiguesSelect from "<src>/components/LiguesSelect";
import app from "next/app";
import handler from "./api/hello";
import data from "<src>/data/teams.json";

export default function Home() {
  const [count, setCount] = useState(0);

  console.log({ data });

  return (
    <>
      <Head>
        <title>Random Football Teams</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={classes.main}>
        <Container maxWidth="sm">
          <Grid
            display={"flex"}
            flexDirection={"column"}
            justifyContent={"center"}
            alignItems={"center"}
          >
            <h1 className="app-title">Random Football Teams</h1>
            <div>
              <LiguesSelect data={data} />
            </div>
          </Grid>
        </Container>
      </main>
    </>
  );
}
