import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "<src>/styles/Home.module.css";
import { useEffect, useState } from "react";
import { Container, Grid } from "@mui/material";
import classes from "<src>/styles/index.styles";
import LiguesSelect from "<src>/components/LiguesSelect";
import app from "next/app";
import handler from "./api/hello";
import data from "<src>/data/teams.json";
import TeamPowerSelect from "<src>/components/TeamPowerSelect";
import versusLogo from "../../public/versus.png";

export default function Home() {
  const [count, setCount] = useState(0);

  console.log({ data });

  return (
    <>
      <Head>
        <title>Random Football Teams</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={classes.main}>
        <Container maxWidth="sm">
          <Grid
            display={"flex"}
            flexDirection={"column"}
            justifyContent={"center"}
            alignItems={"center"}
          >
            <h1 className="app-title">Random Football Teams</h1>
            <div className="selectBoxesWrapper">
              <LiguesSelect data={data} />
              <TeamPowerSelect data={data} />
            </div>
            <div className="generateTeamsWrapper">
              <div>
                <img src="https://upload.wikimedia.org/wikipedia/tr/5/52/FC.Porto.png" />
              </div>
              <Image
                src={versusLogo}
                alt="Picture of the author"
                className="versus"
              />
              <div>
                <img src="https://upload.wikimedia.org/wikipedia/en/thumb/4/40/Boavista_F.C._logo.svg/1200px-Boavista_F.C._logo.svg.png" />
              </div>
            </div>
          </Grid>
        </Container>
      </main>
    </>
  );
}
